import {
  AirVent,
  Anchor,
  AppWindow,
  Axe,
  BetweenHorizontalStart,
  BetweenVerticalStart,
  Blend,
  Bolt,
  BrickWall,
  BriefcaseBusiness,
  BringToFront,
  BrushCleaning,
  Bubbles,
  Cable,
  CassetteTape,
  Circle,
  CircleDot,
  CircleGauge,
  CirclePower,
  Cog,
  Construction,
  Container,
  Crosshair,
  Cylinder,
  Disc,
  Disc3,
  DiscAlbum,
  DoorClosed,
  DoorClosedLocked,
  Drill,
  Droplets,
  Factory,
  Fence,
  Film,
  FlameKindling,
  FlaskConical,
  Glasses,
  Grid2x2,
  Grip,
  GripHorizontal,
  Hammer,
  Hand,
  HardHat,
  HousePlug,
  KeyRound,
  Lamp,
  Lightbulb,
  Link2,
  LocateFixed,
  LockKeyhole,
  Nut,
  Orbit,
  Paintbrush,
  Paintbrush2,
  PaintBucket,
  PaintRoller,
  PenLine,
  PenTool,
  Pickaxe,
  Pipette,
  Plug,
  Plug2,
  PocketKnife,
  Power,
  Router,
  ScanLine,
  Scissors,
  ScissorsLineDashed,
  Settings,
  ShieldCheck,
  ShieldEllipsis,
  Shirt,
  Shovel,
  Sparkle,
  Sprout,
  SquareDashedBottom,
  SquarePower,
  ToggleLeft,
  Toolbox,
  Trees,
  Truck,
  Unplug,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const categoryIconMap = {
  airVent: AirVent,
  anchor: Anchor,
  appWindow: AppWindow,
  axe: Axe,
  betweenHorizontalStart: BetweenHorizontalStart,
  betweenVerticalStart: BetweenVerticalStart,
  blend: Blend,
  bolt: Bolt,
  brickWall: BrickWall,
  briefcaseBusiness: BriefcaseBusiness,
  bringToFront: BringToFront,
  brushCleaning: BrushCleaning,
  bubbles: Bubbles,
  cable: Cable,
  cassetteTape: CassetteTape,
  circle: Circle,
  circleDot: CircleDot,
  circleGauge: CircleGauge,
  circlePower: CirclePower,
  cog: Cog,
  construction: Construction,
  container: Container,
  crosshair: Crosshair,
  cylinder: Cylinder,
  disc: Disc,
  disc3: Disc3,
  discAlbum: DiscAlbum,
  doorClosed: DoorClosed,
  doorClosedLocked: DoorClosedLocked,
  drill: Drill,
  droplets: Droplets,
  factory: Factory,
  fence: Fence,
  film: Film,
  flameKindling: FlameKindling,
  flaskConical: FlaskConical,
  glasses: Glasses,
  grid2x2: Grid2x2,
  grip: Grip,
  gripHorizontal: GripHorizontal,
  hammer: Hammer,
  hand: Hand,
  hardHat: HardHat,
  housePlug: HousePlug,
  keyRound: KeyRound,
  lamp: Lamp,
  lightbulb: Lightbulb,
  link2: Link2,
  locateFixed: LocateFixed,
  lockKeyhole: LockKeyhole,
  nut: Nut,
  orbit: Orbit,
  paintbrush: Paintbrush,
  paintbrush2: Paintbrush2,
  paintBucket: PaintBucket,
  paintRoller: PaintRoller,
  penLine: PenLine,
  penTool: PenTool,
  pickaxe: Pickaxe,
  pipette: Pipette,
  plug: Plug,
  plug2: Plug2,
  pocketKnife: PocketKnife,
  power: Power,
  router: Router,
  scanLine: ScanLine,
  scissors: Scissors,
  scissorsLineDashed: ScissorsLineDashed,
  settings: Settings,
  shieldCheck: ShieldCheck,
  shieldEllipsis: ShieldEllipsis,
  shirt: Shirt,
  shovel: Shovel,
  sparkle: Sparkle,
  sprout: Sprout,
  squareDashedBottom: SquareDashedBottom,
  squarePower: SquarePower,
  toggleLeft: ToggleLeft,
  toolbox: Toolbox,
  trees: Trees,
  truck: Truck,
  unplug: Unplug,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type CategoryIconKey = keyof typeof categoryIconMap;

const reverseCategoryIconMap = new Map<LucideIcon, CategoryIconKey>(
  Object.entries(categoryIconMap).map(([key, icon]) => [icon, key as CategoryIconKey])
);

export const categoryIconOptions = Object.entries(categoryIconMap).map(([key]) => ({
  key: key as CategoryIconKey,
  label: key,
}));

export function isCategoryIconKey(value: unknown): value is CategoryIconKey {
  return typeof value === "string" && value in categoryIconMap;
}

export function getCategoryIcon(iconKey?: string | null) {
  if (!iconKey || !isCategoryIconKey(iconKey)) {
    return categoryIconMap.grid2x2;
  }

  return categoryIconMap[iconKey];
}

export function getCategoryIconKey(icon: LucideIcon) {
  return reverseCategoryIconMap.get(icon) ?? "grid2x2";
}
